### ISSUE TITLE
Time stamps reset on transfer

### ISSUE THREAD

**Issue by mikae1** [ganeshrvel/openmtp#218]
Since version 3 it seems that original created/modified date is destroyed (and set to transfer time), which is very sad (because the speed increases are very welcome). 2.x kept the original date/time.

**Comment by paulgurney** [comment]
awesome app! 

I also had this issue on Mac - after transferring photos from phone, the computer file system changes both the `creation date` and the `modifed date` to the transfer time.  this is not ideal.

**Comment by ganeshrvel** [comment]
I will look into it!

**Comment by lar232unrkniero** [comment]
> I will look into it!

I can fully confirm this problem with the current OpenMTP 3.1.5 version.

Tested with an Android 11 phone.

The problem is that OpenMTP does not preserve for `modified date` when users copy files and directories to macOS. The same problem is also with `access date`. 

macOS a Unix like system supports `creation date`, which Android system does not. The logical behavior is when Android users copy files and folders to macOS, set `creation date` as the `modified date` from the source.

Android system generally supports only these 3 timestamps,
- Modified date
- Access date
- Change date (this cannot be influenced by the user)

Unix-like systems (macOS, iOS/iPadOS, FreeBSD) generally support these 4 timestamps
- Modified date
- Access date
- Change date (this cannot be influenced by the user)
- Creation date (also known as Birth time)

Note: You can also start a terminal software and use `stat` command to display the timestamps that are supported.

**Comment by mikae1** [comment]
3.15 has the same problem, but I just want to add that as soon as you switch to legacy transfer mode, it works as intended (dates are kept intact).

**Comment by ganeshrvel** [comment]
working on it.

**Comment by ronyeh** [comment]
Thanks for your hard work on this project! I think my issue is related to this. I have a GoPro that I connect to my macbook via MTP mode. When I drag a MP4 or JPG over to my computer, I would prefer if the file's creation / modification timestamp information was identical to what they are on the GoPro's SD card. Right now, the timestamps are set to the transfer time. (Ideally I would not have to remove the SD card from the camera all the time to get files with original timestamps.)

**Comment by ronyeh** [comment]
To be more specific, the EXIF information in the JPG files is preserved correctly. So the "image created" field in the EXIF is fine.

However, I'd like if the file system timestamps were also set to be identical to the file system timestamps on the SD card / GoPro camera. This is most important for MP4 files, since they do not contain EXIF information.

**Comment by ganeshrvel** [comment]
fixed in https://github.com/ganeshrvel/openmtp/issues/218. 

Closing

**Comment by ganeshrvel** [comment]
Please update to the latest version

cc: @lar232unrkniero @mikae1 @paulgurney @ronyeh

**Comment by ganeshrvel** [comment]
For those who need a quick patch to correct the creation and modification date/time for their videos/images transferred to macbook via OpenMTP, you may run this script.

It will read the exif information of images or videos and update the creation and modification date/time of those file.

This should fix the wrongly sorted (by date) of images and videos in your file manager or the photos app.

### WARNING: BACKUP your files before running this script.

### Note:
```
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
```


Instructions in the README file:
[https://github.com/ganeshrvel/openmtp-update-files-to-system-time](https://github.com/ganeshrvel/openmtp-update-files-to-system-time)

**Comment by landry314** [comment]
This is STILL a problem. I just downloaded the newest version ad STILL you are not preserving timestamps. it is a simple flag. "cp -p" in the shell. adb push and pull preserve timestamps. android file manager being the awful software that it is, DOES PRESERVE DATES. What is going on? I will not use this software until you don't set ALL MY FILE DATES AND TIMES to the current time. Why is this so hard? I am going back to the terminal. Wow.

**Comment by ganeshrvel** [comment]
Hi @landry314 there are limitations to the gomtpfs library that we use in the application. It doesn't really give away a lot of "useful" information, though this is by far the most stable mtp package out there. We don't use adb for a lot of other reasons.


As I have mentioned earlier in one of the other threads, mtp is an old technology. It has a lot of misses. I'd wish that someday Google replaces the crappy mtp with adb after fixing it's shortcomings.
