### ISSUE TITLE
Can't open OpenMTP

### ISSUE THREAD

**Issue by dwivedisshyam** [ganeshrvel/openmtp#367]
**Prerequisites**

- [ ] Have you reviewed the steps in the following link to see if they address your issue? 
  - https://github.com/ganeshrvel/openmtp/issues/276

**Describe the bug**
After installing OpenMTP, I'm not able to open it. It asks me to move to app to bin with the error shown in the screenshot.

**Attachments**
Include if relevant,
1. Open your Terminal and run the following code:
```shell
zip -r -X ~/Desktop/OpenMTP-log.zip "$HOME/Library/Application Support/io.ganeshrvel.openmtp/logs/"
```
2. Attach the file *OpenMTP-log.zip* found in your Desktop folder here.

Or

1. Open the App,
2. Click on Help > Report Bugs.
3. Generate and send us the bugs report.

**Screenshots**
<img width="674" alt="Screenshot 2024-05-18 at 23 55 05" src="https://github.com/ganeshrvel/openmtp/assets/32840389/2b83cc26-9737-42f7-9968-d3a54a8506d3">

**Comment by vivekteega** [comment]
What MacOS version is this being installed on? 
Also have you tried opening the app with the following instructions: Hold Command button and right click over the app icon -> Click open

**Comment by dwivedisshyam** [comment]
I'm on mac `Version 14.5 (23F79)`

**Comment by ganeshrvel** [comment]
Hi.

Could you try downloading openmtp from this url: https://github.com/ganeshrvel/openmtp/releases/download/v3.2.20/openmtp-3.2.20-mac-arm64.dmg ? 

Do let me know if it worked for you.

Remember to delete any other versions of OpenMTP from your desktop and Applications folders.

**Comment by a-fortunato** [comment]
> Hi.
> 
> Could you try downloading openmtp from this url: https://github.com/ganeshrvel/openmtp/releases/download/v3.2.20/openmtp-3.2.20-mac-arm64.dmg ?
> 
> Do let me know if it worked for you.
> 
> Remember to delete any other versions of OpenMTP from your desktop and Applications folders.

I downloaded it from there but got the same error as @dwivedisshyam said.

> have you tried opening the app with the following instructions: Hold Command button and right click over the app icon -> Click open

This worked though (only when doing it directly in Finder's Applications folder).
A new pop up appears, but now you can click "Open" instead.

**Comment by ganeshrvel** [comment]
Hello @a-fortunato 

Could you share the screenshots of the error?
Also please mention your os version and mac book model name.

**Comment by a-fortunato** [comment]
hi @ganeshrvel 

This is my mac version and model
<img width="276" alt="Screenshot 2024-06-10 at 23 20 28" src="https://github.com/ganeshrvel/openmtp/assets/6339463/f6da6697-f152-40b3-923a-470314302f76">


This is the original error (I uninstalled it so I could show it to you)
<img width="296" alt="Screenshot 2024-06-10 at 23 23 52" src="https://github.com/ganeshrvel/openmtp/assets/6339463/867735bb-1c42-4fb5-80bf-e901cd7c52d1">

I hope it's helpful!

**Comment by ganeshrvel** [comment]
Thanks for reporting this @a-fortunato @dwivedisshyam   

This was caused by a bug in node-gyp in the build system. 

We fixed it in the release: [v3.2.23](https://github.com/ganeshrvel/openmtp/releases/tag/v3.2.23)

Download the version for your macOS architecture:
- Apple Silicon: [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.23/openmtp-3.2.23-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.23/openmtp-3.2.23-mac-arm64.dmg)
- Intel Macs: [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.23/openmtp-3.2.23-mac-x64.dmg ](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.23/openmtp-3.2.23-mac-x64.dmg )

PR URL: [https://github.com/ganeshrvel/openmtp/pull/372](https://github.com/ganeshrvel/openmtp/pull/372)


Please close the issue if it is solved for you.
Cheers

**Comment by vanawaker** [comment]
Hey,

I'm experiencing an issue with version 3.2.23. After installing it, the app gets stuck at launch and won't open. I've tried uninstalling and reinstalling it, as well as restarting my Mac, but nothing seems to work. 
However, then I try install the older version 3.2.20, it opens without any issues. Could you please check if the latest update has caused any problems? I've turned off automatic updates for now. Thanks!

**Comment by ganeshrvel** [comment]
Hi @vanawaker can you please check if you have downloaded the Apple Silicon specific version? https://github.com/ganeshrvel/openmtp/releases/download/v3.2.23/openmtp-3.2.23-mac-arm64.dmg

**Comment by vanawaker** [comment]
@ganeshrvel yes, I've tried Apple Silicon first, won't open, then tried the intel version, still won't open, stuck in the same way, Now I'm using the Apple Silicon version 3.2.20, and it's working fine with no issues.

**Comment by ganeshrvel** [comment]
Certainly! Here's a revised version of your reply for GitHub:

---

Hi,

Thanks for confirming.

Could you please try the following steps and send me the results?

1. Open the app using the command:

```
/Applications/OpenMTP.app/Contents/MacOS/OpenMTP
```
and send me the output from the terminal.

2. Send me the error logs by running this command:

```
open ~/Library/Application\ Support/io.ganeshrvel.openmtp/logs/
```

3. Compress the logs and email them to me at ganeshrvel@outlook.com.

I will look into this as soon as possible.

Thank you!

**Comment by ganeshrvel** [comment]
I have made the app as a prerelease version until i find a fix to this issue.

**Comment by ganeshrvel** [comment]
Hi @vanawaker,

Regarding the issue: The app gets stuck at launch and won't open.

Issue details:
Machine ID generation was throwing an exception which was looping and causing `Maximum call stack size exceeded`.

Fix:
I fixed it in the release: [v3.2.24](https://github.com/ganeshrvel/openmtp/releases/tag/v3.2.24)

Download the version for your macOS architecture:
- Apple Silicon: [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.24/openmtp-3.2.24-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.24/openmtp-3.2.24-mac-arm64.dmg)
- Intel Macs: [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.24/openmtp-3.2.24-mac-x64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.24/openmtp-3.2.24-mac-x64.dmg)

PR URL: [https://github.com/ganeshrvel/openmtp/pull/379](https://github.com/ganeshrvel/openmtp/pull/379)

This is a prerelease version. Let me know if it worked for you.

Cheers

**Comment by vanawaker** [comment]
Hi @ganeshrvel 

Thanks for the update, I've tried the v3.2.24 Apple Silicon, and it works! It opens without issue, 

Thanks!
